[2024-12-13 03:27:28,599] INFO _log() L97    * Restarting with stat - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-13 03:35:00,855] ERROR log_exception() L875  Exception on /leads [GET] - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ~~~~~~~~~~~~~~~~~~~~~^^^^
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
    ...<5 lines>...
    )
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a set.
[2024-12-13 03:35:00,857] INFO _log() L97   127.0.0.1 - - [13/Dec/2024 03:35:00] "[35m[1mGET /leads HTTP/1.1[0m" 500 - - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-13 03:35:04,837] ERROR log_exception() L875  Exception on /leads [GET] - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ~~~~~~~~~~~~~~~~~~~~~^^^^
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
    ...<5 lines>...
    )
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a set.
[2024-12-13 03:35:04,838] INFO _log() L97   127.0.0.1 - - [13/Dec/2024 03:35:04] "[35m[1mGET /leads HTTP/1.1[0m" 500 - - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-13 03:35:05,243] ERROR log_exception() L875  Exception on /leads [GET] - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ~~~~~~~~~~~~~~~~~~~~~^^^^
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
    ...<5 lines>...
    )
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a set.
[2024-12-13 03:35:05,244] INFO _log() L97   127.0.0.1 - - [13/Dec/2024 03:35:05] "[35m[1mGET /leads HTTP/1.1[0m" 500 - - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-13 03:35:05,450] ERROR log_exception() L875  Exception on /leads [GET] - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ~~~~~~~~~~~~~~~~~~~~~^^^^
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
    ...<5 lines>...
    )
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a set.
[2024-12-13 03:35:05,451] INFO _log() L97   127.0.0.1 - - [13/Dec/2024 03:35:05] "[35m[1mGET /leads HTTP/1.1[0m" 500 - - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-13 03:35:05,634] ERROR log_exception() L875  Exception on /leads [GET] - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py L875 
Traceback (most recent call last):
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ~~~~~~~~~~~~~~~~~~~~~^^^^
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\flask\app.py", line 1249, in make_response
    raise TypeError(
    ...<5 lines>...
    )
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a set.
[2024-12-13 03:35:05,635] INFO _log() L97   127.0.0.1 - - [13/Dec/2024 03:35:05] "[35m[1mGET /leads HTTP/1.1[0m" 500 - - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-13 03:40:09,278] INFO _log() L97   127.0.0.1 - - [13/Dec/2024 03:40:09] "[35m[1mGET /leads HTTP/1.1[0m" 500 - - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-13 03:40:11,571] INFO _log() L97   127.0.0.1 - - [13/Dec/2024 03:40:11] "[35m[1mGET /leads HTTP/1.1[0m" 500 - - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-13 03:40:11,889] INFO _log() L97   127.0.0.1 - - [13/Dec/2024 03:40:11] "[35m[1mGET /leads HTTP/1.1[0m" 500 - - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\werkzeug\_internal.py L97  
[2024-12-13 03:40:12,062] INFO _log() L97   127.0.0.1 - - [13/Dec/2024 03:40:12] "[35m[1mGET /leads HTTP/1.1[0m" 500 - - call_trace=C:\Matheus\Eng Software\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\MVP\MVP_api\amb_api\Lib\site-packages\werkzeug\_internal.py L97  
